// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: recordalerting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Problem_ProblemType int32

const (
	Problem_UNKNOWN               Problem_ProblemType = 0
	Problem_MISSING_WEIGHT        Problem_ProblemType = 1
	Problem_MISSING_FILED         Problem_ProblemType = 2
	Problem_MISSING_WIDTH         Problem_ProblemType = 3
	Problem_MISSING_CONDITION     Problem_ProblemType = 4
	Problem_MISSING_SLEEVE        Problem_ProblemType = 5
	Problem_NEEDS_KEEPER          Problem_ProblemType = 6
	Problem_NEEDS_DIGITAL         Problem_ProblemType = 7
	Problem_NEEDS_SALE_BUDGET     Problem_ProblemType = 8
	Problem_NEEDS_SOLD_DETAILS    Problem_ProblemType = 9
	Problem_BAD_BANDCAMP          Problem_ProblemType = 10
	Problem_STALE_LIMBO           Problem_ProblemType = 11
	Problem_EXPIRED_SALE          Problem_ProblemType = 12
	Problem_MISSING_NOTES         Problem_ProblemType = 13
	Problem_MISSING_PACKAGE_SCORE Problem_ProblemType = 14
)

// Enum value maps for Problem_ProblemType.
var (
	Problem_ProblemType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "MISSING_WEIGHT",
		2:  "MISSING_FILED",
		3:  "MISSING_WIDTH",
		4:  "MISSING_CONDITION",
		5:  "MISSING_SLEEVE",
		6:  "NEEDS_KEEPER",
		7:  "NEEDS_DIGITAL",
		8:  "NEEDS_SALE_BUDGET",
		9:  "NEEDS_SOLD_DETAILS",
		10: "BAD_BANDCAMP",
		11: "STALE_LIMBO",
		12: "EXPIRED_SALE",
		13: "MISSING_NOTES",
		14: "MISSING_PACKAGE_SCORE",
	}
	Problem_ProblemType_value = map[string]int32{
		"UNKNOWN":               0,
		"MISSING_WEIGHT":        1,
		"MISSING_FILED":         2,
		"MISSING_WIDTH":         3,
		"MISSING_CONDITION":     4,
		"MISSING_SLEEVE":        5,
		"NEEDS_KEEPER":          6,
		"NEEDS_DIGITAL":         7,
		"NEEDS_SALE_BUDGET":     8,
		"NEEDS_SOLD_DETAILS":    9,
		"BAD_BANDCAMP":          10,
		"STALE_LIMBO":           11,
		"EXPIRED_SALE":          12,
		"MISSING_NOTES":         13,
		"MISSING_PACKAGE_SCORE": 14,
	}
)

func (x Problem_ProblemType) Enum() *Problem_ProblemType {
	p := new(Problem_ProblemType)
	*p = x
	return p
}

func (x Problem_ProblemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Problem_ProblemType) Descriptor() protoreflect.EnumDescriptor {
	return file_recordalerting_proto_enumTypes[0].Descriptor()
}

func (Problem_ProblemType) Type() protoreflect.EnumType {
	return &file_recordalerting_proto_enumTypes[0]
}

func (x Problem_ProblemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Problem_ProblemType.Descriptor instead.
func (Problem_ProblemType) EnumDescriptor() ([]byte, []int) {
	return file_recordalerting_proto_rawDescGZIP(), []int{1, 0}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problems      []*Problem             `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_recordalerting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_recordalerting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_recordalerting_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetProblems() []*Problem {
	if x != nil {
		return x.Problems
	}
	return nil
}

type Problem struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 Problem_ProblemType    `protobuf:"varint,1,opt,name=type,proto3,enum=recordalerting.Problem_ProblemType" json:"type,omitempty"`
	InstanceId           int64                  `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	IssueNumber          int32                  `protobuf:"varint,3,opt,name=issue_number,json=issueNumber,proto3" json:"issue_number,omitempty"`
	IssueOpenedTimestamp int64                  `protobuf:"varint,4,opt,name=issue_opened_timestamp,json=issueOpenedTimestamp,proto3" json:"issue_opened_timestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_recordalerting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_recordalerting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_recordalerting_proto_rawDescGZIP(), []int{1}
}

func (x *Problem) GetType() Problem_ProblemType {
	if x != nil {
		return x.Type
	}
	return Problem_UNKNOWN
}

func (x *Problem) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Problem) GetIssueNumber() int32 {
	if x != nil {
		return x.IssueNumber
	}
	return 0
}

func (x *Problem) GetIssueOpenedTimestamp() int64 {
	if x != nil {
		return x.IssueOpenedTimestamp
	}
	return 0
}

var File_recordalerting_proto protoreflect.FileDescriptor

const file_recordalerting_proto_rawDesc = "" +
	"\n" +
	"\x14recordalerting.proto\x12\x0erecordalerting\"=\n" +
	"\x06Config\x123\n" +
	"\bproblems\x18\x01 \x03(\v2\x17.recordalerting.ProblemR\bproblems\"\xf5\x03\n" +
	"\aProblem\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.recordalerting.Problem.ProblemTypeR\x04type\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\x03R\n" +
	"instanceId\x12!\n" +
	"\fissue_number\x18\x03 \x01(\x05R\vissueNumber\x124\n" +
	"\x16issue_opened_timestamp\x18\x04 \x01(\x03R\x14issueOpenedTimestamp\"\xb6\x02\n" +
	"\vProblemType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eMISSING_WEIGHT\x10\x01\x12\x11\n" +
	"\rMISSING_FILED\x10\x02\x12\x11\n" +
	"\rMISSING_WIDTH\x10\x03\x12\x15\n" +
	"\x11MISSING_CONDITION\x10\x04\x12\x12\n" +
	"\x0eMISSING_SLEEVE\x10\x05\x12\x10\n" +
	"\fNEEDS_KEEPER\x10\x06\x12\x11\n" +
	"\rNEEDS_DIGITAL\x10\a\x12\x15\n" +
	"\x11NEEDS_SALE_BUDGET\x10\b\x12\x16\n" +
	"\x12NEEDS_SOLD_DETAILS\x10\t\x12\x10\n" +
	"\fBAD_BANDCAMP\x10\n" +
	"\x12\x0f\n" +
	"\vSTALE_LIMBO\x10\v\x12\x10\n" +
	"\fEXPIRED_SALE\x10\f\x12\x11\n" +
	"\rMISSING_NOTES\x10\r\x12\x19\n" +
	"\x15MISSING_PACKAGE_SCORE\x10\x0eB.Z,github.com/brotherlogic/recordalerting/protob\x06proto3"

var (
	file_recordalerting_proto_rawDescOnce sync.Once
	file_recordalerting_proto_rawDescData []byte
)

func file_recordalerting_proto_rawDescGZIP() []byte {
	file_recordalerting_proto_rawDescOnce.Do(func() {
		file_recordalerting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recordalerting_proto_rawDesc), len(file_recordalerting_proto_rawDesc)))
	})
	return file_recordalerting_proto_rawDescData
}

var file_recordalerting_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recordalerting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recordalerting_proto_goTypes = []any{
	(Problem_ProblemType)(0), // 0: recordalerting.Problem.ProblemType
	(*Config)(nil),           // 1: recordalerting.Config
	(*Problem)(nil),          // 2: recordalerting.Problem
}
var file_recordalerting_proto_depIdxs = []int32{
	2, // 0: recordalerting.Config.problems:type_name -> recordalerting.Problem
	0, // 1: recordalerting.Problem.type:type_name -> recordalerting.Problem.ProblemType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recordalerting_proto_init() }
func file_recordalerting_proto_init() {
	if File_recordalerting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recordalerting_proto_rawDesc), len(file_recordalerting_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recordalerting_proto_goTypes,
		DependencyIndexes: file_recordalerting_proto_depIdxs,
		EnumInfos:         file_recordalerting_proto_enumTypes,
		MessageInfos:      file_recordalerting_proto_msgTypes,
	}.Build()
	File_recordalerting_proto = out.File
	file_recordalerting_proto_goTypes = nil
	file_recordalerting_proto_depIdxs = nil
}
